language: cpp
compiler:
  - clang
  - gcc
before_install:
  - cat /etc/issue.net
  - sudo apt-get update
  - sudo apt-get install -y libogre-dev libois-dev libopenal-dev libvorbis-dev liblua5.1-dev liblua50-dev liblualib50-dev bash
script:
  - mkdir ./build
  - cd ./build
  - cmake ..
  - nproc
  - make -j4
notifications:
  email: false
