# Find OIS library
#
# OIS_INCLUDE_DIR      where to find the include files
# OIS_LIBRARY_DIR      where to find the libraries
# OIS_LIBRARIES        list of libraries to link
# OIS_FOUND            true if OIS was found

SET( OIS_LIBRARYDIR / CACHE PATH "Alternative library directory" )
SET( OIS_INCLUDEDIR / CACHE PATH "Alternative include directory" )
MARK_AS_ADVANCED( OIS_LIBRARYDIR OIS_INCLUDEDIR )

FIND_LIBRARY( OIS_LIBRARY_DIR OIS PATHS ${OIS_LIBRARYDIR} )
FIND_PATH( OIS_INCLUDE_DIR OIS/OIS.h PATHS ${OIS_INCLUDEDIR} )

GET_FILENAME_COMPONENT( OIS_LIBRARY_DIR ${OIS_LIBRARY_DIR} PATH )

IF( OIS_INCLUDE_DIR AND OIS_LIBRARY_DIR )
    SET( OIS_LIBRARIES OIS )
    SET( OIS_FOUND TRUE )
ELSE( OIS_INCLUDE_DIR AND OIS_LIBRARY_DIR )
    SET( OIS_FOUND FALSE )
ENDIF( OIS_INCLUDE_DIR AND OIS_LIBRARY_DIR )
