# Find LUALIB50 library
#
# LUALIB50_INCLUDE_DIR      where to find the include files
# LUALIB50_LIBRARY_DIR      where to find the libraries
# LUALIB50_LIBRARIES        list of libraries to link
# LUALIB50_FOUND            true if LUALIB50 was found

SET( LUALIB50_LIBRARYDIR / CACHE PATH "Alternative library directory" )
SET( LUALIB50_INCLUDEDIR / CACHE PATH "Alternative include directory" )
MARK_AS_ADVANCED( LUALIB50_LIBRARYDIR LUALIB50_INCLUDEDIR )

FIND_LIBRARY( LUALIB50_LIBRARY_DIR OgreMain PATHS ${LUALIB50_LIBRARYDIR} )
FIND_PATH( LUALIB50_INCLUDE_DIR lualib.h
           HINTS "/usr/include/lua50" "/usr/include"
           PATHS ${LUALIB50_INCLUDEDIR} )

GET_FILENAME_COMPONENT( LUALIB50_LIBRARY_DIR ${LUALIB50_LIBRARY_DIR} PATH )

IF( LUALIB50_INCLUDE_DIR AND LUALIB50_LIBRARY_DIR )
    SET( LUALIB50_LIBRARIES lualib50 lua50)
    SET( LUALIB50_FOUND TRUE )
ELSE( LUALIB50_INCLUDE_DIR AND LUALIB50_LIBRARY_DIR )
    SET( LUALIB50_FOUND FALSE )
ENDIF( LUALIB50_INCLUDE_DIR AND LUALIB50_LIBRARY_DIR )
